# Generated by Django 3.0.3 on 2020-02-08 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_index', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('food_type', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable')], default='fruit', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=25, unique=True)),
                ('index', models.IntegerField()),
                ('guid', models.UUIDField(unique=True)),
                ('has_died', models.BooleanField(default=False)),
                ('currency_symbol', models.CharField(choices=[('$', '$')], default='$', max_length=2)),
                ('balance', models.FloatField()),
                ('picture', models.URLField()),
                ('age', models.IntegerField()),
                ('eye_color', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('registered', models.DateTimeField()),
                ('friends_csv', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('greeting', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civilisation.Company')),
                ('favourite_food', models.ManyToManyField(to='civilisation.FoodItem')),
                ('tags', models.ManyToManyField(to='civilisation.CitizenTag')),
            ],
        ),
    ]
