# Generated by Django 3.0.3 on 2020-02-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='currency_symbol',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='balance',
            field=models.CharField(max_length=25),
        ),
    ]
